### ISSUE TITLE
Error(s) in loading state_dict for IQAModel

### ISSUE THREAD

**Issue by splinter21** [lidq92/LinearityIQA#1]
RuntimeError: Error(s) in loading state_dict for IQAModel:
	Missing key(s) in state_dict: "regr6.0.weight", "regr6.0.bias", "regr6.1.weight", "regr6.1.bias", "regr6.1.running_mean", "regr6.1.running_var", "regr7.0.weight", "regr7.0.bias", "regr7.1.weight", "regr7.1.bias", "regr7.1.running_mean", "regr7.1.running_var", "regression.0.weight", "regression.0.bias", "regression.1.weight", "regression.1.bias", "regression.1.running_mean", "regression.1.running_var". 
	Unexpected key(s) in state_dict: "regr6.weight", "regr6.bias", "regr7.weight", "regr7.bias", "regression.weight", "regression.bias".

The weights are downloaded from baidu drive.

**Comment by lidq92** [comment]
@splinter21 Based on your error information, I guess you have set the `--use_bn_end` option. You should be aware of the fact that the checkpoints provided are the final model weights without the `--use_bn_end` option (as we have verified that "bnMSE" is worse than the proposed "Norm-in-Norm" in Figure 4).

I would suggest you read and follow the `README.md` and `results_in_the_paper/README.md` patiently.
For example, you will know the provided checkpoints are saved from the "Training on KonIQ-10k" section of `README.md`.

If you really want to get the checkpoints with the `--use_bn_end` option, please refer to the section "Figure 4" of `results_in_the_paper/README.md` or `python main.py --help` for the training help.

Besides the content in this repo, you can also read our preprint manuscript with supplemental materials on arXiv.

Good luck!

**Comment by splinter21** [comment]
Yes, it's caused by the "--use_bn_end" option. Now it's ok.
