### ISSUE TITLE
Cannot download checkpoints

### ISSUE THREAD

**Issue by cs20162004** [lidq92/LinearityIQA#10]
Hello, Thank you for providing the code. I tried to download your checkpoints (from pan.baidu.com) but it asks for account which asks for Chinese phone number. Can you please provide another way to download your model weights such as Google Drive?

**Comment by lidq92** [comment]
@cs20162004 Thank you for your interest!
It is hard for me to upload big files to Google Drive or Dropbox. 
Currently, I am trying to upload the checkpoints to One Drive, and I would update the comment with the shared link (maybe tomorrow).

**Comment by lidq92** [comment]
@cs20162004 Sorry, it is still too hard and too slow for me to upload the checkpoints to One Drive.
I do not know why it stops uploading at 1.0G/1.0G.
I have also tried to send them through Gmail.
If you can provide me a temporal IP, user name, and password of a PC by email, I can send the files to you with remote copy `scp`.
Or any other way?
For example, when I search "**How to download Baiduyun file without account**" by Google, I got [this simple guide](https://steemit.com/baidu/@havila/how-to-download-from-baidu-without-an-account), or [this](https://www.reddit.com/r/Piracy/comments/auhyxk/how_do_i_download_from_panbaidu/?ref=share&ref_source=embed&utm_content=title&utm_medium=post_embed&utm_name=f8a809e9fde24673bb14f57d8aaa59c3&utm_source=embedly&utm_term=auhyxk), etc.
I do not know whether it works. Maybe you can have a try.

Finally, if I succeed in uploading the checkpoints to Google Drive/Dropbox/One Drive, I will update the links as soon as possible.

**Comment by lidq92** [comment]
@cs20162004 Hi Ali,

I have uploaded the checkpoints to your aws server.

Best,
Dingquan

**Comment by GauravKudva** [comment]
Hello, I am also having the same problem as @cs20162004. Could you kindly provide an alternative link from which I could download the model checkpoints ?

**Comment by lidq92** [comment]
@GauravKudva Thank you for your interest! Unfortunately, I cannot upload the model checkpoints to Google Drive due to the network issue.

The way for solving @cs20162004 's problem is that he sent me the information about his (aws) server, and I uploaded the files to the server. I could do this for you if you can also provide me a server to upload files.

And you can also follow README to train the model to get the checkpoints, which won't take you too much time.

Maybe there is another way if Ali is able to share these checkpoints.
@cs20162004 Could you please help me by sharing an alternative link (e.g., Google Drive) for downloading the model checkpoints (that I send to you)? So that @GauravKudva can reach the model checkpoints.
Thank you.

**Comment by GauravKudva** [comment]
Thank you for your reply @lidq92 . Would it be possible for you to transfer the checkpoints through WeTransfer or will you face the same problem due to network issues ?

**Comment by lidq92** [comment]
@GauravKudva Sorry, I tried to open [WeTransfer](https://wetransfer.com) but failed.

Let's wait a few days to see whether Ali could give us a hand if there are no other feasible ways.

**Comment by cs20162004** [comment]
Hello @lidq92,

Sure, here is the link to the checkpoints on Google Drive:

https://drive.google.com/drive/folders/1S5XljhTyKsFkRclhijXBM6SrcD5Tov6Z?usp=sharing

**Comment by lidq92** [comment]
@cs20162004 Thanks!

**Comment by GauravKudva** [comment]
Thanks a lot @cs20162004 and @lidq92 for your assistance.

**Comment by Alexkkir** [comment]
[link to google drive](https://drive.google.com/drive/folders/1S5XljhTyKsFkRclhijXBM6SrcD5Tov6Z?usp=sharing) doesn't work

**Comment by lidq92** [comment]
@Alexkkir I would try to upload the checkpoint to Google Drive.
