### ISSUE TITLE
The result of cosine_similarity in  IQALoss

### ISSUE THREAD

**Issue by shuishiwojiade** [lidq92/LinearityIQA#12]
Hello, Thank you for sharing the great work. But I have a confusion in 109th line of code in IQA
Outputs and Targets are tensors of **B** * 1, so the value of the element in the **rho** is 1 or -1

**Comment by lidq92** [comment]
@shuishiwojiade 
Oh, it is a wrong implementation. Thank you for pointing it out!
The correct one should be `rho =  torch.cosine_similarity(y_pred.t(), y.t())`.
This may affect the result of `𝑙 + 0.1𝑙′` in Table 2.
I have corrected this code (See https://github.com/lidq92/LinearityIQA/commit/7936bb811ae9409f1858e4d8f558d8153091edcf) and have updated the result of the combination of `𝑙` and `𝑙′` in this repo (See https://github.com/lidq92/LinearityIQA/commit/b2f10477aca9e6cf307ad86297759d0b7c308470).
Thank you again.
