### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by yinglili666** [lidq92/LinearityIQA#13]
Hello, when I execute "CUDA"_ VISIBLE_ DEVICES=0 python  main.py  --dataset KonIQ-10k --resize --exp_ id 0 --lr 1e-4 -bs 8 -e 30 --ft_ lr_ ratio 0.1 --arch resnext101_ 32x8d --loss_ type norm-in-norm --p 1 --q 2 > exp_ id=0-resnext101_ 32x8d-p = 1-Q = 2-664x498. Log 2 > & 1 & " ,  the terminal outputs" [1] 11303 "directly without any training;  Another command directly outputs "[2] 2264 [1] Exit 1".

**Comment by lidq92** [comment]
it is running in the background. 
Use `tail -f exp_ id=0-resnext101_ 32x8d-p = 1-Q = 2-664x498. Log` to see the log file.
Or you can run the command `CUDA_ VISIBLE_ DEVICES=0 python main.py --dataset KonIQ-10k --resize --exp_ id 0 --lr 1e-4 -bs 8 -e 30 --ft_ lr_ ratio 0.1 --arch resnext101_ 32x8d --loss_ type norm-in-norm --p 1 --q 2` directly.

**Comment by yinglili666** [comment]
Thank you! I'll try again.













At 2021-03-26 15:28:18, "李鼎权, Dingquan Li" ***@***.***> wrote:

it is running in the background.
Use tail -f exp_ id=0-resnext101_ 32x8d-p = 1-Q = 2-664x498. Log to see the log file.
Or you can run the command CUDA_ VISIBLE_ DEVICES=0 python main.py --dataset KonIQ-10k --resize --exp_ id 0 --lr 1e-4 -bs 8 -e 30 --ft_ lr_ ratio 0.1 --arch resnext101_ 32x8d --loss_ type norm-in-norm --p 1 --q 2 directly.

**Comment by lidq92** [comment]
@yinglili666 
By the way, a suggestion: use `htop` or `top`, `nvidia-smi` or `gpustat -i` to see the state of your CPUs and GPUs

**Comment by yinglili666** [comment]
Do I need to execute the command "rm-rf apex"? But there are some errors with deleting or not deleting that.

**Comment by lidq92** [comment]
@yinglili666 You need to follow the `README` and execute the command `rm-rf apex`. If you encountered some error, this means that you have not successfully installed the environment, especially the `apex` package. 

So the only suggestion is that please follow `README`. 

You may ask someone else nearby to help you with programming since I found you are a freshman (e.g., you did not know the meaning of `2 > & 1 &` and you did not know whether you have successfully installed the packages).

Good luck!

**Comment by yinglili666** [comment]
> @yinglili666 You need to follow the `README` and execute the command `rm-rf apex`. If you encountered some error, this means that you have not successfully installed the environment, especially the `apex` package.
> 
> So the only suggestion is that please follow `README`.
> 
> You may ask someone else nearby to help you with programming since I found you are a freshman (e.g., you did not know the meaning of `2 > & 1 &` and you did not know whether you have successfully installed the packages).
> 
> Good luck!

Thanks for your reply.
