### ISSUE TITLE
How to use 'DistributedDataParallel '?

### ISSUE THREAD

**Issue by ciwei123** [lidq92/LinearityIQA#16]
@lidq92  Thanks for your sharing. I want to train the model by multi-gpu.
①I use the `torch.nn.DataParallel` from (https://github.com/lidq92/MDTVSFA/issues/1)
But I find that the gpu0 memory is very large , the others gpu memory is very small. I think I don't make good use of the multi-gpu.So I select the `DistributedDataParallel`
②`DistributedDataParallel`
But I get the warning:
`/root/anaconda3/lib/python3.6/site-packages/ignite/metrics/metric.py:216: RuntimeWarning: IQAPerformance class does not support distributed setting. Computed result is not collected across all computing devices`
the error:
`writer = SummaryWriter(log_dir='{}/{}-{}'.format(args.log_dir, args.format_str, current_time))`
`FileExistsError: [Errno 17] File exists: 'runs/m'`

Could you tell me how to make good use of multi-gpu? Thank you very much!!

**Comment by SuperBruceJia** [comment]
> @lidq92 Thanks for your sharing. I want to train the model by multi-gpu.
> ①I use the `torch.nn.DataParallel` from ([lidq92/MDTVSFA#1](https://github.com/lidq92/MDTVSFA/issues/1))
> But I find that the gpu0 memory is very large , the others gpu memory is very small. I think I don't make good use of the multi-gpu.So I select the `DistributedDataParallel`
> ②`DistributedDataParallel`
> But I get the warning:
> `/root/anaconda3/lib/python3.6/site-packages/ignite/metrics/metric.py:216: RuntimeWarning: IQAPerformance class does not support distributed setting. Computed result is not collected across all computing devices`
> the error:
> `writer = SummaryWriter(log_dir='{}/{}-{}'.format(args.log_dir, args.format_str, current_time))`
> `FileExistsError: [Errno 17] File exists: 'runs/m'`
> 
> Could you tell me how to make good use of multi-gpu? Thank you very much!!

Hi,

Have you tried to use a larger Batch Size while using `nn.DataParallel` function?

**Comment by lidq92** [comment]
> @lidq92 Thanks for your sharing. I want to train the model by multi-gpu.
> ①I use the `torch.nn.DataParallel` from ([lidq92/MDTVSFA#1](https://github.com/lidq92/MDTVSFA/issues/1))
> But I find that the gpu0 memory is very large , the others gpu memory is very small. I think I don't make good use of the multi-gpu.So I select the `DistributedDataParallel`
> ②`DistributedDataParallel`
> But I get the warning:
> `/root/anaconda3/lib/python3.6/site-packages/ignite/metrics/metric.py:216: RuntimeWarning: IQAPerformance class does not support distributed setting. Computed result is not collected across all computing devices`
> the error:
> `writer = SummaryWriter(log_dir='{}/{}-{}'.format(args.log_dir, args.format_str, current_time))`
> `FileExistsError: [Errno 17] File exists: 'runs/m'`
> 
> Could you tell me how to make good use of multi-gpu? Thank you very much!!

You can try "model parallel". See [model-parallelism-using-multiple-gpus](https://pytorch.org/docs/stable/pipeline.html#model-parallelism-using-multiple-gpus) for more details.

**Comment by ciwei123** [comment]
> > @lidq92 Thanks for your sharing. I want to train the model by multi-gpu.
> > ①I use the `torch.nn.DataParallel` from ([lidq92/MDTVSFA#1](https://github.com/lidq92/MDTVSFA/issues/1))
> > But I find that the gpu0 memory is very large , the others gpu memory is very small. I think I don't make good use of the multi-gpu.So I select the `DistributedDataParallel`
> > ②`DistributedDataParallel`
> > But I get the warning:
> > `/root/anaconda3/lib/python3.6/site-packages/ignite/metrics/metric.py:216: RuntimeWarning: IQAPerformance class does not support distributed setting. Computed result is not collected across all computing devices`
> > the error:
> > `writer = SummaryWriter(log_dir='{}/{}-{}'.format(args.log_dir, args.format_str, current_time))`
> > `FileExistsError: [Errno 17] File exists: 'runs/m'`
> > Could you tell me how to make good use of multi-gpu? Thank you very much!!
> 
> Hi,
> 
> Have you tried to use a larger Batch Size while using `nn.DataParallel` function?

@SuperBruceJia If I use a larger Batch Size,it will be worse.

**Comment by ciwei123** [comment]
> > @lidq92 Thanks for your sharing. I want to train the model by multi-gpu.
> > ①I use the `torch.nn.DataParallel` from ([lidq92/MDTVSFA#1](https://github.com/lidq92/MDTVSFA/issues/1))
> > But I find that the gpu0 memory is very large , the others gpu memory is very small. I think I don't make good use of the multi-gpu.So I select the `DistributedDataParallel`
> > ②`DistributedDataParallel`
> > But I get the warning:
> > `/root/anaconda3/lib/python3.6/site-packages/ignite/metrics/metric.py:216: RuntimeWarning: IQAPerformance class does not support distributed setting. Computed result is not collected across all computing devices`
> > the error:
> > `writer = SummaryWriter(log_dir='{}/{}-{}'.format(args.log_dir, args.format_str, current_time))`
> > `FileExistsError: [Errno 17] File exists: 'runs/m'`
> > Could you tell me how to make good use of multi-gpu? Thank you very much!!
> 
> You can try "model parallel". See [model-parallelism-using-multiple-gpus](https://pytorch.org/docs/stable/pipeline.html#model-parallelism-using-multiple-gpus) for more details.

@lidq92 Thanks for your reply, I will learn that method.

**Comment by SuperBruceJia** [comment]
> > > @lidq92 Thanks for your sharing. I want to train the model by multi-gpu.
> > > ①I use the `torch.nn.DataParallel` from ([lidq92/MDTVSFA#1](https://github.com/lidq92/MDTVSFA/issues/1))
> > > But I find that the gpu0 memory is very large , the others gpu memory is very small. I think I don't make good use of the multi-gpu.So I select the `DistributedDataParallel`
> > > ②`DistributedDataParallel`
> > > But I get the warning:
> > > `/root/anaconda3/lib/python3.6/site-packages/ignite/metrics/metric.py:216: RuntimeWarning: IQAPerformance class does not support distributed setting. Computed result is not collected across all computing devices`
> > > the error:
> > > `writer = SummaryWriter(log_dir='{}/{}-{}'.format(args.log_dir, args.format_str, current_time))`
> > > `FileExistsError: [Errno 17] File exists: 'runs/m'`
> > > Could you tell me how to make good use of multi-gpu? Thank you very much!!
> > 
> > 
> > Hi,
> > Have you tried to use a larger Batch Size while using `nn.DataParallel` function?
> 
> @SuperBruceJia If I use a larger Batch Size,it will be worse.

I also found that the performances of (Wa)DIQaM were unsatisfactory, e.g., around 0.5 SRCC, and couldn't meet the results as shown in the original paper while using a larger batch size (Paper: 4 VS my Setting: 256 or 512). I think if we used a larger batch size, for one iteration, the update of loss might be a litter variant compared with small batch size.

Anyway, when I used a larger batch size, the usage of GPUs' resources and memory surged. I believe if there is a better performance, we could try to use a larger batch size for other algorithms. 

Meanwhile, you can definitely tell us how to manipulate multiple GPUs efficiently after you keep your codes running. 

Thanks in advance and have a nice day!

**Comment by lidq92** [comment]
@SuperBruceJia Larger batch size means fewer iterations given the same training epochs. You may try more training epochs to update the parameters if you use a larger batch size in an algorithm.

@ciwei123 You may want to check whether the loss values are collected or the predicted values are collected from different GPUs. It would have no effect on a sample-wise loss (e.g., L1, L2) but it would affect batch-correlated loss. If the loss values are collected, this just means you update the parameters for every #GPUs iteration with the same batch size used in a GPU. To enlarge a larger batch size for training the network with a batch-correlated loss, you need to collect the predicted quality values before calculating the loss. The way I suggest for you in my last comment is a solution.

It seems a larger batch size is preferred for a batch-correlated loss (e.g., 4<8<16),  while it is certainly not true for a sample-wise loss (8>16). One can determine the batch size or other parameters based on the validation performance.

**Comment by SuperBruceJia** [comment]
> @SuperBruceJia Larger batch size means fewer iterations given the same training epochs. You may try more training epochs to update the parameters if you use a larger batch size in an algorithm.
> 
> @ciwei123 You may want to check whether the loss values are collected or the predicted values are collected from different GPUs. It would have no effect on a sample-wise loss (e.g., L1, L2) but it would affect batch-correlated loss. If the loss values are collected, this just means you update the parameters for every #GPUs iteration with the same batch size used in a GPU. To enlarge a larger batch size for training the network with a batch-correlated loss, you need to collect the predicted quality values before calculating the loss. The way I suggest for you in my last comment is a solution.
> 
> It seems a larger batch size is preferred for a batch-correlated loss (e.g., 4<8<16), while it is certainly not true for a sample-wise loss (8>16). One can determine the batch size or other parameters based on the validation performance.

Dear Brother Dingquan, thanks a lot for your information and guide.
