### ISSUE TITLE
What is the reason of using the ImageNet model as the pretrained model?

### ISSUE THREAD

**Issue by ciwei123** [lidq92/LinearityIQA#18]
@lidq92 Thanks for your sharing .Could you tell met the reason of using the ImageNet model as the pretrained model? What about using the detection model or other task model？Thank you very much!!!

**Comment by lidq92** [comment]
It has been verified in many subjective and objective evaluation methods that visual quality depends on image content, which can be effectively expressed by the features extracted from pre-trained ImageNet classification models.

You can also explore the effectiveness & power of features extracted from other vision tasks if you want.

**Comment by ciwei123** [comment]
@lidq92 Thanks for your reply. Yes, I find that many papers use the pre-trained ImageNet classification models. Have you tried other vision tasks model as the pretrained model? And do you find some papers use other tasks model as the pretrained model? Thank you very much!!
