### ISSUE TITLE
the dataset files are imgs and csvs

### ISSUE THREAD

**Issue by splinter21** [lidq92/LinearityIQA#2]
http://database.mmsp-kn.de/koniq-10k-database.html

the score and indicator files are csvs file now

and I find that in test_dataset.py, that's .mat.

is there a dataloader/dataset.py that adapts .csv file?

**Comment by lidq92** [comment]
@splinter21 You can just use the mat file which is converted from the CSV file.

I prefer using the mat file, but you can make corresponding changes to the `IQAdataset` for adopting other file formats, e.g., the CSV format. It won't be a difficulty if you have previously handled CSV files using Python. 

For example, you can use `pandas` for reading the CSV file just like [this url](https://github.com/subpic/koniq/blob/master/train_koncept512.ipynb).

**Comment by splinter21** [comment]
Thanks，I will have a try.
