### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by LizzieOneDay** [lidq92/LinearityIQA#20]
Hello, when I train the network, I met this error:

 Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0                                                                                                                                                            
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0                                                                                                                                                            
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 8192.0                                                                                                                                                             
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 4096.0                                                                                                                                                             
Current run is terminating due to exception: Output should have 2 items of the same length, got 2 and 3, 2                                                                                                                                 
Engine run is terminating due to exception: Output should have 2 items of the same length, got 2 and 3, 2                                                                                                                                  
Engine run is terminating due to exception: Output should have 2 items of the same length, got 2 and 3, 2  

And I don't know how to solve it, Please help me , thank you!

**Comment by lidq92** [comment]
@LizzieOneDay Sorry I did not meet this error. 
You can locate where does the error occur ("Output should have 2 items of the same length, got 2 and 3, 2"). Maybe you have modified the code, e.g., the original predictions are three scores and you changed them into one score？

The information you provided was not enough for me to give further comments.  Please follow readme and install the correct version of each package (Sometimes it is the issue of different package version, e.g., torch, ignite, etc.).
If you have problem in apex, to run this code, you can also delete the things related to apex which I just used it for memory saving.

**Comment by LizzieOneDay** [comment]
@lidq92 thank you very much. I have removed the code related to apex, and the training is normal.
