### ISSUE TITLE
link to model chechpoints is broken

### ISSUE THREAD

**Issue by Alexkkir** [lidq92/LinearityIQA#24]
Hello! In [this](https://github.com/lidq92/LinearityIQA/issues/10#issuecomment-783497363) issue you made a link to model checkpoint, stored on google drive. Unfortunately, now this link doesn't work. Can you please check, if everything is correct?

**Comment by lidq92** [comment]
@Alexkkir [link to google drive](https://drive.google.com/drive/folders/1S5XljhTyKsFkRclhijXBM6SrcD5Tov6Z?usp=sharing) is shared by @cs20162004. Can you try downloading [checkpoints](https://pan.baidu.com/s/1MRamimHWX8F-SOQ_QsIrvg) on pan.baidu with a password `4z7z`?

**Comment by lidq92** [comment]
@Alexkkir https://drive.google.com/drive/folders/1H79ptqjcR4NH6HP4wLsEmqwhNqNNqXwh?usp=sharing

**Comment by lidq92** [comment]
@Alexkkir [link to google drive](https://drive.google.com/drive/folders/1S5XljhTyKsFkRclhijXBM6SrcD5Tov6Z?usp=sharing) is shared by @cs20162004

**Comment by Alexkkir** [comment]
I'm from Russia and i can't use baidu, cause this site available for use only in China/Japan.
Link to google drive which you mentioned doesn't work. It throws error 404 not found
