### ISSUE TITLE
apex==0.1 can't be installed by pip

### ISSUE THREAD

**Issue by splinter21** [lidq92/LinearityIQA#4]
There is no version 0.1 of apex in pip,

and installing other version is not ok.

I clone the codes from github-apex and install from source.
When using, I use sys.path.append("apex-codes-path") in the head of main.py.

And the problem is solved.

**Comment by lidq92** [comment]
@splinter21 Thank you for pointing it out.
I installed the apex from the [source](https://github.com/NVIDIA/apex) (by following the `README.md`), too.
No need to add `sys.path.append("apex-codes-path")` if you have installed apex in your enviroment.

When I clean up my code, I run `pip freeze > requirements.txt` and get that the `apex` version I used is `0.1`.

I have given more details on the `README.md` about (apex) installation, see [commit/35482a1
](https://github.com/lidq92/LinearityIQA/commit/35482a1fdc5f5d4bdc65ff3740a11ce7e6a4f5ef).
