### ISSUE TITLE
How does "resize" influence the performance?

### ISSUE THREAD

**Issue by splinter21** [lidq92/LinearityIQA#5]
I think downsampling may degrade the quality of images and may cause blurry.
And the training set we can get has already been downsampled. (otherwise they can't be easily in the same resolution)
Should we resize again for the data augmentation? Or just crop the image for training?

**Comment by splinter21** [comment]
The default setting in the codes is "resize to 498x664" and "crop to 498x498", why?

**Comment by lidq92** [comment]
@splinter21 We do not use crop in the experiments. We resize the image to 664x498 for a better tradeoff between computation efficiency and prediction performance, and the reader should be aware that the resize operation is not for data augmentation.

Maintaining a larger resolution may obtain better performance, you can see my comments on Figure 5 in this [README.md](https://github.com/lidq92/LinearityIQA/tree/master/results_in_the_paper).
We also provide the file for plotting the model performance under different resolutions.

To explore and understanding the effect of image resolution, you can obviously run experiments with different resolutions.
After you run the experiments with different image resolutions, you can plot the results for visualization with `image_size_performance_plot.py`.

**Comment by splinter21** [comment]
So I should set "crop_size_h" to 768 and ""crop_size_w" to 1024 for training? Or set "augment"to False?

**Comment by splinter21** [comment]
So I should set "crop_size_h" to 498 and ""crop_size_w" to 664 for training? Or set "augment"to False?

**Comment by lidq92** [comment]
@splinter21 Default value for `augment` is `False`. Again, **we do not use data augmentation for all the experiments**, although I have implemented it.

Please run `python main.py -h` to get more help, for example, you will see the option `resize_size_h` and `resize_size_w` for setting the size for resized images.

I would also suggest you read into the codes, at least when you have any questions, for example, you will see lines 50-51 in `IQAdataset.py` for the resize operation, and then you will know how to set the resolution of the resized images.

**Comment by splinter21** [comment]
When training (default), neither "resize" nor "crop" should be used, but when testing, "resize" can be used for a quicker inference (a better trade-off).

Is it right?

**Comment by lidq92** [comment]
@splinter21 In our experiments, during training and testing, we resize images to 664x498, as you can find relevant descriptions in our paper. Correspondingly, we always use `--resize` and set the `resize` option to `True`, which you can see in two `README.md` files in this repo.

**Comment by splinter21** [comment]
Clear, thanks!
